---
- name: Install Nagios Server
  hosts: nagios
  remote_user: ansible
  become: yes
  vars:
    ansible_system_user: ansible
    nagios_plugin_path: /usr/lib64/nagios/plugins
    nagios_username: nagiosadmin
    nagios_password: password
    nagios_create_guest_user: true
    nagios_ro_username: guest
    nagios_ro_password: password
    nagios_http_port: 80
    nagios_https_port: 443
    admin_name_01: nagiosadmin
    admin_email_01: nagiosadmin@ziyotek5.local
    nagios_host_monitor_swap: true
    dns_check_domain: ziyotek5.local
    kibana_user: admin
    kibana_password: admin
    jenkins_user: jenkinsadmin
    jenkins_pass: password
    oobserver_user: admin
    oobserver_pass: admin
    snmp_mib_path: /usr/share/snmp/mibs
    snmp_opts: -v2c -c public

# - name: Check Operating System
#   fail:
#     msg="You're not running a supported operating system (CentOS or RHEL 7+)"
#   when: ((ansible_os_family != "RedHat") or (ansible_distribution_major_version|int < 7))

  roles:
    - { role: nagios }
