---
- name: Install initial packages
  hosts: web573

  remote_user: ansible
  become: yes 
  tasks: 
    - name: install all initial packages
      yum: 
        name: ['man', 'man-pages', 'mlocate', 'vim', 'bind-utils', 'git', 'python3', 'epel-release', 'sysstat']

        state: latest

    - name: Install chrony packages
      yum: 
        name: chrony
        state: latest 

    - name: configure chrony 
      template: 
        src: /ansible/Pro-SavvySix/ansible/playbooks/templates/chrony.conf.j2
        dest: /etc/chrony.conf

    - name: start chronyd
      service:
        name: chronyd
        state: started
