---
- name: Install Docker and PIP
  hosts: docker
  remote_user: ansible
  become: yes

  roles: 
    # - common.yml
    # - resolve.yml
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.ansible
    - atosatto.docker-swarm 
