---
- name: Configure Httpd for Web Servers
  hosts: web573
  remote_user: ansible
  become: yes
  tasks:
    - name: Add httpd configuration file 
      template:
        src: http.conf.j2
        dest: /etc/httpd/conf/httpd.conf
    
    - name: Restart Httpd
      service:
        name: httpd
        state: restarted
        enabled: yes

        