---
- name: Install Kubernetes and Docker
  hosts: kubew
  remote_user: ansible
  become: yes 

  vars: 
    kubernetes_role: "node"
    kubernetes_allow_pods_on_master: true
  
  roles:
    - geerlingguy.pip
    - geerlingguy.docker 
    - geerlingguy.kubernetes
