---
- name: Install Kubernetes and Docker
  hosts: kubernetescluster
  remote_user: ansible
  become: true

  vars: 
    kubernetes_allow_pods_on_master: false
  
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

