---
- name: Install initial packages
  hosts: web6

  remote_user: ansible
  become: yes 
  tasks: 
    - name: install all initial packages
      yum: 
        name: ['man', 'man-pages', 'mlocate', 'vim', 'bind-utils', 'git', 'python3', 'epel-release', 'sysstat']

        state: latest

    - name: Install ntp packages
      yum: 
        name: ntp
        state: latest 

    - name: configure ntp
      template: 
        src: /ansible/Pro-SavvySix/ansible/playbooks/templates/ntp.conf.j2
        dest: /etc/ntp

    - name: start ntp
      service:
        name: ntpd
        state: started

    - name: Stop and disable Chrony 
      service: 
        name: chronyd
        state: stopped 