---
- name: Install Samba Server and Client 
  hosts: web573
  remote_user: ansible
  become: yes  
  roles: 
    - geerlingguy.samba
  
- name: Configure Samba Clients
    template:
      src: smb.conf.j2
      dest: /etc/samba/smb.conf
    
      backup: yes
      
# - name: Create Samba ueser admin
#   raw: useradd admin
#   raw: smbpasswd -a admin
#   raw: password
#   raw: password