---
- name: configure Samba Clients
  hosts: [ web7, web6 ]
  remote_user: ansible
  become: yes 
  roles:
    - geerlingguy.samba


    # - name: Configure Samba Clients
    #   template:
    #     src: smb.conf.j2
    #     dest: /etc/samba/smb.conf
    #     backup: yes
      
    # - name: Create Samba ueser admin
    #   raw: useradd jacobo
    #   raw: smbpasswd -a jacobo
    #   raw: password
    #   raw: password 